#!/bin/bash
KEYFILE="./mykey.key"
CERTFILE="./mycert.crt"
if [ $# > 1 ]; then
        $KEYFILE=$1 ;
fi
if [ $# > 2 ]; then
        $CERTFILE=$2 ;
fi

/usr/bin/openssl genrsa -out $KEYFILE 1024
echo "

"
/usr/bin/openssl req -new -key $KEYFILE -out mycert.csr
/usr/bin/openssl x509 -req -days 365 -in mycert.csr -signkey $KEYFILE -out $CERTFILE
rm mycert.csr
