/******************************************************************************
 * Authors: Tolu Alabi
 *          Zach Butler
 *          Martin Dluhos
 *
 * Created: February 21, 2012
 * Revised: March 7, 2012
 * Description: This file contains functions which format the verification
 * response and functions which send the response back to the client.
 ******************************************************************************/

#include "response.h"
#include "certificate.h"
#include <openssl/rsa.h>
#include <openssl/sha.h>
#include <openssl/pem.h>

//WE ARE NOT SURE ABOUT THIS
#define RESPONSE_LEN 201
#define MAX_NO_OF_CERTS 7

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Helpers
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

/* Allocate and fill the answer string field in connection struct. */
void
set_answer_string(struct connection_info_struct* connection_info, char* answer_string)
{  
  connection_info->answer_string = malloc(sizeof(char) * strlen(answer_string + 1));
  strcpy((char*)connection_info->answer_string, answer_string);
}

/* Generate a signature of a fingerprint list.
 * @param fingerprint_list list of fingerprints
 * @param signature string to hold the digital signature of fingerprints
 * @return 1 on success, 0 on otherwise
 */
int
generate_signature(unsigned char *fingerprint_list, unsigned char *signature,
                   unsigned int *signature_size, RSA *private_key)
{
  unsigned char *return_val;
  /* Digest generated by SHA-1. */
  unsigned char digest[SHA_DIGEST_LENGTH];
  
  /* Generate a SHA-1 digest of the fingerprint list. */
  return_val = SHA1(fingerprint_list, SHA_DIGEST_LENGTH, digest);
  
  if (return_val == NULL)
    return 0;
 
  /* Generate a signature of the digest using the notary's private key. */
  return RSA_sign(NID_sha1, digest, SHA_DIGEST_LENGTH, signature,
                  signature_size, private_key);
} // generate_signature

/* Obtains a response to a POST/GET request.
 */
int
retrieve_response (void *coninfo_cls, host *host_to_verify, const char *fingerprint_from_client)
{
  int verified, num_of_certs; // was certificate verified?
  char *fingerprints_from_website[MAX_NO_OF_CERTS];
  char *json_fingerprint_list; // the response to send to client
  unsigned int *signature_size = NULL;
  unsigned char *signature;
  RSA *private_key;
  FILE *key_file = fopen(key_filename, "r");

  struct connection_info_struct *con_info = coninfo_cls;

  //variables to store the time stamp
  size_t start_time, end_time;

  //create space for the fingerprints
  int i;
  for(i=0; i<MAX_NO_OF_CERTS; i++)
    fingerprints_from_website[i] = calloc(sizeof(char) * FPT_LENGTH, 1);

  //get the fingerprints
  start_time = time(NULL);
  num_of_certs = request_certificate(host_to_verify, fingerprints_from_website);
  
  if (num_of_certs == 0)
    {
      /* The notary could not obtain the certificate from the website
       * for some reason.
       */
      con_info->answer_code = MHD_HTTP_SERVICE_UNAVAILABLE; //503
      return MHD_NO;
    } // if

  if (fingerprint_from_client != NULL)
    {
      verified =
        verify_certificate (fingerprint_from_client, fingerprints_from_website, num_of_certs);

      if (verified == 1)
        con_info->answer_code = MHD_HTTP_OK; // 200
      else
        {
          con_info->answer_code = MHD_HTTP_CONFLICT; // 409
        }
    }
  else con_info->answer_code = MHD_HTTP_OK;

  /* Format the response which will be sent to client.
   * Note that this response is sent both on a successful verification
   * and on a failed verification.
   * The JSON format of the response is available at
   * https://github.com/moxie0/Convergence/wiki/Notary-Protocol
   */
  //get end_time for processing the request
  end_time = time(NULL);

  json_fingerprint_list = malloc ( (RESPONSE_LEN + 1) * sizeof (char));
  sprintf (json_fingerprint_list,
           "{\n \
\t\"fingerprintList\":\n \
\t[\n \
\t {\n \
\t \"timestamp\": {\"start\": \"%Zu\", \"finish\": \"%Zu\"},\n \
\t \"fingerprint\": \"%s\"\n \
\t }\n \
\t]\n\
}\n", start_time, end_time, fingerprints_from_website[0]);

   /* Get the RSA private key from a file. */
  private_key = PEM_read_RSAPrivateKey(key_file, NULL, NULL, NULL);

  /* Calculate the signature size and allocate space for it. */
  *signature_size = RSA_size(private_key);
  signature = (unsigned char *) malloc (*signature_size);

  generate_signature((unsigned char *) json_fingerprint_list, signature, signature_size, private_key);

  set_answer_string(con_info, json_fingerprint_list);
  
  free(json_fingerprint_list);

  //free memory used for fingerprints
  for(i=0; i<MAX_NO_OF_CERTS; i++)
    free(fingerprints_from_website[i]);

  return MHD_YES;
}


/* Sends response back to the client. This function could be a wrapper for
 * send_page.
 */
int
send_response (struct MHD_Connection *connection, const char *response_data,
               int status_code)
{
  int return_value;
  struct MHD_Response *response;

  response = MHD_create_response_from_data (strlen(response_data), (void*) response_data,
                                            MHD_NO, MHD_NO);
  if (response == NULL)
  {
    return MHD_NO;
  }

  return_value = MHD_queue_response (connection, status_code, response);
  MHD_destroy_response (response);

  return return_value;
}
